<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>MTG.Scryfall.Importer</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="NewFile1.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MTG.Importer.Models\MTG.Importer.Models.csproj" />
    <ProjectReference Include="..\MTG.Scryfall.Models\MTG.Scryfall.Models.csproj" />
  </ItemGroup>

</Project>
