<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Scriptorium.Mtg.Scryfall.Importer</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="NewFile1.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Runtime.Caching" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Scriptorium.Mtg.Importer.Models\Scriptorium.Mtg.Importer.Models.csproj" />
    <ProjectReference Include="..\Scriptorium.Mtg.Importer.Save\Scriptorium.Mtg.Importer.Save.csproj" />
    <ProjectReference Include="..\Scriptorium.Mtg.Scryfall.Models\Scriptorium.Mtg.Scryfall.Models.csproj" />
  </ItemGroup>

</Project>
